# Generated by Django 3.0.8 on 2020-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200709_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='aboutAs',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='aboutUs',
            field=models.TextField(default=''),
        ),
    ]
