# Generated by Django 3.0.8 on 2020-07-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_runtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtitle',
            name='key',
            field=models.CharField(default='', max_length=30),
        ),
    ]
