# Generated by Django 3.0.8 on 2020-07-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_services_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='button',
        ),
    ]
