# Generated by Django 3.0.8 on 2020-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_services_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='button',
            field=models.BooleanField(default=None),
        ),
    ]
