# Generated by Django 3.1.1 on 2020-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(default='', max_length=50)),
                ('slogan', models.CharField(default='', max_length=50)),
                ('about', models.TextField(default='')),
                ('aboutSlogan', models.CharField(default='', max_length=50)),
                ('servicesSlogan', models.CharField(default='', max_length=50)),
                ('formTitle', models.CharField(default='', max_length=30)),
                ('formText', models.CharField(default='', max_length=100)),
                ('footerSlogan', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Основная информация',
                'verbose_name_plural': 'Основная информация',
            },
        ),
    ]
