# Generated by Django 3.1.1 on 2020-09-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='aboutSlogan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='formTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='mainTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='servicesSlogan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='slogan',
            field=models.CharField(default='', max_length=100),
        ),
    ]
