# Generated by Django 3.1.1 on 2020-09-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0002_auto_20200920_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garanty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('title', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Гарантии',
                'verbose_name_plural': 'Гарантии',
            },
        ),
    ]
