# Generated by Django 3.1.1 on 2020-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0003_garanty'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='adress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='companyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='facebook',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='telegram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='vk',
            field=models.CharField(default='', max_length=100),
        ),
    ]
