# Generated by Django 3.1.1 on 2020-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0004_auto_20200925_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('title', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Цели',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
