# Generated by Django 3.1.1 on 2020-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0006_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('pageName', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
                ('picture', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Блок услуг',
                'verbose_name_plural': 'Блок услуг',
            },
        ),
    ]
