# Generated by Django 3.1.1 on 2020-10-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0007_serviceblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceblock',
            options={'verbose_name': 'Блоки услуг', 'verbose_name_plural': 'Блоки услуг'},
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('serviceBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sovet.serviceblock')),
            ],
            options={
                'verbose_name': 'Секции услуг',
                'verbose_name_plural': 'Секции услуг',
            },
        ),
    ]
