# Generated by Django 3.1.1 on 2020-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0008_auto_20201002_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceblock',
            options={'verbose_name': 'Блок услуг', 'verbose_name_plural': 'Блок услуг'},
        ),
        migrations.AlterModelOptions(
            name='servicesection',
            options={'verbose_name': 'Секция услуг', 'verbose_name_plural': 'Секция услуг'},
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='title2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
