# Generated by Django 3.1.1 on 2020-10-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0009_auto_20201002_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent', models.CharField(default='', max_length=5)),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
                ('serviceSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sovet.servicesection')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
