# Generated by Django 3.1.1 on 2020-10-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0010_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accent',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='title2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
