# Generated by Django 3.1.1 on 2020-10-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0011_auto_20201008_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Секции услуг',
                'verbose_name_plural': 'Секции услуг',
            },
        ),
    ]
