# Generated by Django 3.1.1 on 2020-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0014_auto_20201019_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
